### ISSUE TITLE
Show commands output when running run-extra-commands

### ISSUE THREAD

**Issue by mariajgrimaldi** [eduNEXT/tutor-contrib-picasso#6]
Currently, this is the output when running this sequence of extra commands:

```
PICASSO_EXTRA_COMMANDS:
- tutor plugins index add https://raw.githubusercontent.com/eduNEXT/tutor-plugin-indexes/main/
- tutor picasso enable-themes
- tutor config save
```

```
➜  redwood tutor picasso run-extra-commands


Configuration saved to /home/mgmdy/Work/Envs/Local/redwood/config.yml
Environment generated in /home/mgmdy/Work/Envs/Local/redwood/env
```
Which is not very informative. Can we consider printing the output of all commands executed?

**Comment by MaferMazu** [comment]
We are printing the output here: https://github.com/eduNEXT/tutor-contrib-picasso/blob/main/tutorpicasso/commands/run_extra_commands.py#L100.

We can improve the outputs of the `enable-themes` and `enable-private-packages` so that the `run-extra-command` can print the information better.
